# Конфиг цветов от kitty не подойдет. Генерируй шаблон для alacritty (.toml) через matugen и раскомментируй строку ниже:
# import = ["~/.config/alacritty/themes/matugen.toml"]

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.5

[window.padding]
x = 10
y = 5

[font.normal]
family = "JetBrains Mono"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[cursor.style]
shape = "Beam"
blinking = "On"

# cursor_trail и enable_graphics в alacritty не поддерживаются
