#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
     kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
    kb_variant = intl
    follow_mouse = 1
    sensitivity  = 0
    
    touchpad {
        natural_scroll = false
    }
}


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

