$terminal = alacritty
$fileManager = thunar
$menu = rofi -show drun
$clipboard = cliphist list
$mainMod = SUPER

bind = $mainMod, X, exec, $terminal
bind = $mainMod, D, exec, $menu
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, exec, $clipboard | rofi -dmenu | cliphist decode | wl-copy
bind = $mainMod, R, exec, $HOME/.config/hypr/scripts/wallpapers/set-random.sh

bind = , F1, exec, bash ~/.config/hypr/scripts/infinite-desktop/mode-switch.sh infinite
bind = , F2, exec, bash ~/.config/hypr/scripts/infinite-desktop/mode-switch.sh tiling

bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, F, togglefloating,

bind = $mainMod, left,  exec, bash ~/.config/hypr/scripts/infinite-desktop/hypr-navigate.sh left
bind = $mainMod, right, exec, bash ~/.config/hypr/scripts/infinite-desktop/hypr-navigate.sh right
bind = $mainMod, up,    exec, bash ~/.config/hypr/scripts/infinite-desktop/hypr-navigate.sh up
bind = $mainMod, down,  exec, bash ~/.config/hypr/scripts/infinite-desktop/hypr-navigate.sh down

bind = $mainMod SHIFT, left,  movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up,    movewindow, u
bind = $mainMod SHIFT, down,  movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod, Tab, workspace, previous
bind = $mainMod ALT, left,  workspace, -1
bind = $mainMod ALT, right, workspace, +1

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind  = $mainMod, mouse_down, workspace, +1
bind  = $mainMod, mouse_up,   workspace, -1
bindm = $mainMod, mouse:272, movewindow


bindel = ,XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp,   exec, brightnessctl s 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-

bind = $mainMod,       PRINT, exec, hyprshot -m window
bind = ,               PRINT, exec, hyprshot -m output
bind = $mainMod SHIFT, S,     exec, hyprshot -m region




bind = ALT,       Tab, exec, bash ~/.config/hypr/scripts/infinite-desktop/alttab.sh
bind = ALT SHIFT, Tab, exec, bash ~/.config/hypr/scripts/infinite-desktop/alttab.sh prev
bind  = SUPER SHIFT, mouse:272, exec, bash -c 'echo start > /tmp/infinite-drag-state'
bindr = SUPER SHIFT, mouse:272, exec, bash -c 'echo end   > /tmp/infinite-drag-state'
bind = $mainMod, W, exec, killall -SIGUSR1 waybar
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bindm = SUPER SHIFT, mouse:273, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = $mainMod, B, exec, ~/.config/hypr/scripts/infinite-desktop/toggle_opacity.sh
