# Variables
$inFocusOpacity = 0.9
$notInFocusOpacity = 0.7

windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


# Kitty fully opaque

# Browsers

# Spotify / Discord / Telegram / VS Code / Thunar or Nemo by title

# Lunar Client fullscreen (static effect)
windowrule = fullscreen on, match:class ^Lunar Client.*$

windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class nm-connection-editor
