windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class wallpaper-picker
windowrule = size 80% 65%, match:class wallpaper-picker
windowrule = center on, match:class wallpaper-picker
windowrule = opacity 1.0 override 1.0 override, match:class wallpaper-picker
windowrule = animation "popin 80%", match:class wallpaper-picker
windowrule = dim_around true, match:class wallpaper-picker
windowrule = float on, match:class monitor-settings
windowrule = size 50% 60%, match:class monitor-settings
windowrule = center on, match:class monitor-settings
windowrule = opacity 1.0 override 1.0 override, match:class monitor-settings
windowrule = animation "popin 80%", match:class monitor-settings
windowrule = dim_around true, match:class monitor-settings

windowrule = fullscreen on, match:class swayimg
