$wallpaper = {{image}}

$background = rgb({{colors.surface.dark.hex_stripped}})
$foreground = rgb({{colors.on_surface.dark.hex_stripped}})

$color0 = rgb({{colors.surface_container_lowest.dark.hex_stripped}})
$color1 = rgb({{colors.primary.dark.hex_stripped}})
$color2 = rgb({{colors.secondary.dark.hex_stripped}})
$color3 = rgb({{colors.tertiary.dark.hex_stripped}})
$color4 = rgb({{colors.primary_container.dark.hex_stripped}})
$color5 = rgb({{colors.secondary_container.dark.hex_stripped}})
$color6 = rgb({{colors.tertiary_container.dark.hex_stripped}})
$color7 = rgb({{colors.on_surface_variant.dark.hex_stripped}})
$color8 = rgb({{colors.outline.dark.hex_stripped}})
$color9 = rgb({{colors.primary.dark.hex_stripped}})
$color10 = rgb({{colors.secondary.dark.hex_stripped}})
$color11 = rgb({{colors.tertiary.dark.hex_stripped}})
$color12 = rgb({{colors.primary_container.dark.hex_stripped}})
$color13 = rgb({{colors.secondary_container.dark.hex_stripped}})
$color14 = rgb({{colors.tertiary_container.dark.hex_stripped}})
$color15 = rgb({{colors.on_surface.dark.hex_stripped}})
