pragma Singleton

import Quickshell
import QtQuick

// Generated by matugen from the current wallpaper (scheme-content, dark).
Singleton {
    id: root

    readonly property color background:       "{{colors.surface.dark.hex}}"
    readonly property color surface:          "{{colors.surface.dark.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.dark.hex}}"
    readonly property color surfaceVariant:   "{{colors.surface_variant.dark.hex}}"

    readonly property color text:             "{{colors.on_surface.dark.hex}}"
    readonly property color subtext:          "{{colors.on_surface_variant.dark.hex}}"
    readonly property color outline:          "{{colors.outline.dark.hex}}"

    readonly property color primary:          "{{colors.primary.dark.hex}}"
    readonly property color primaryText:      "{{colors.on_primary.dark.hex}}"
    readonly property color secondary:        "{{colors.secondary.dark.hex}}"
    readonly property color tertiary:         "{{colors.tertiary.dark.hex}}"
    readonly property color error:            "{{colors.error.dark.hex}}"
    readonly property color success:          "{{colors.tertiary.dark.hex}}"
    readonly property color warning:          "{{colors.secondary.dark.hex}}"

    readonly property color shadow:           "{{colors.shadow.dark.hex}}"
}
