$terminal    = foot
$fileManager = thunar
$browser     = bash -c "zen-browser || firefox || chromium"
$launcher    = bash -c 'hyprlauncher -t || fuzzel'
$editor      = bash -c "zeditor || codium || code"

exec-once = waybar
exec-once = hypridle
exec-once = hyprctl setcursor Qogir-white-cursors 21

env = XCURSOR_THEME, Qogir-white-cursors
env = XCURSOR_SIZE, 21
exec-once = ~/scripts/infinite-desktop.py
exec-once = awww-daemon


xwayland {
  enable = false
}
