render {
    new_render_scheduling = true
}

cursor {
    no_hardware_cursors = true
}

dwindle {
    preserve_split    = true
    force_split       = 2
    precise_mouse_move = true
}

master {
    new_status    = slave
    new_on_active = after
    new_on_top    = false
}


binds {
    scroll_event_delay = 0
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
